name: Acceptance

on:
  pull_request:
    branches: [ main ]

env:
  go_version: 1.16

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
      TEST_ACCEPTANCE: true
      TMP: ${{ github.workspace }}/tmp
      TEMP: ${{ github.workspace }}/tmp
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go_version }}
    - name: Build nix
      run: |
        go install github.com/goreleaser/goreleaser@latest
        ./build.sh
      if: runner.os != 'Windows'
      env:
        HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY_DEV }}
        HONEYCOMB_DATASET: pct_dev
    - name: Build Windows
      run: |
        go install github.com/goreleaser/goreleaser@latest
        ./build.ps1
      if: runner.os == 'Windows'
      env:
        HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY_DEV }}
        HONEYCOMB_DATASET: pct_dev
    - name: Test
      run: go test -v ./acceptance/...
